runnable from os x

diff --git a/scripts/deploy b/scripts/deploy
--- a/scripts/deploy
+++ b/scripts/deploy
@@ -1,8 +1,14 @@
 #!/bin/bash -x
 
-set -e
+set -u                          # Treat unset variables as an error
+set -e #  Exit immediately if a simple command exits with a non-zero status
 
-ABSOLUTE_PATH=$(readlink -f $0)
+READLINK=readlink
+if which greadlink > /dev/null; then
+    READLINK=greadlink
+fi
+
+ABSOLUTE_PATH=$(${READLINK} -f $0)
 RSSMINER_CODE_ROOT="${ABSOLUTE_PATH%/*/*}"
 
 # rm bin classes -rf && lein compile
diff --git a/scripts/run b/scripts/run
--- a/scripts/run
+++ b/scripts/run
@@ -1,8 +1,16 @@
 #!/bin/sh
+set -u                          # Treat unset variables as an error
+set -e #  Exit immediately if a simple command exits with a non-zero status
 
-ABSOLUTE_PATH=$(readlink -f $0)
+READLINK=readlink
+if which greadlink > /dev/null; then
+    READLINK=greadlink
+fi
+
+ABSOLUTE_PATH=$(${READLINK} -f $0)
 HOME="${ABSOLUTE_PATH%/*/*}"
 cd "${HOME}" && java -server \
+    -Xdebug -Xrunjdwp:transport=dt_socket,address=9092,server=y,suspend=n \
     -Dfile.encoding=UTF-8 \
     -Djava.net.preferIPv4Stack=true \
     -Dsun.jnu.encoding=UTF-8 \
